# Generated by Django 4.1.3 on 2022-12-04 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='', upload_to='Images/%Y/%m/%d')),
                ('Name', models.CharField(blank=True, default='', max_length=200)),
                ('ClickedBy', models.CharField(blank=True, default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Short_Description', models.CharField(blank=True, default='', max_length=500)),
                ('Display_in_Products_Page', models.BooleanField(default=True)),
                ('UploadDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
