# Generated by Django 4.1.3 on 2022-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StillMinutePhotographs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='ClickedBy',
            new_name='PhotoGrapher',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='Name',
            new_name='ProductName',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='UploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
