# Generated by Django 4.1.3 on 2022-12-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StillMinutePhotographs', '0003_eventsimages_fineartimages_foodimages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsimages',
            options={'verbose_name_plural': 'EventsImages'},
        ),
        migrations.AlterModelOptions(
            name='fineartimages',
            options={'verbose_name_plural': 'FineArtImages'},
        ),
        migrations.AlterModelOptions(
            name='foodimages',
            options={'verbose_name_plural': 'FoodImages'},
        ),
        migrations.AlterModelOptions(
            name='interiorsimages',
            options={'verbose_name_plural': 'InteriorsImages'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AlterModelOptions(
            name='weddingimages',
            options={'verbose_name_plural': 'WeddingImages'},
        ),
    ]
