# Generated by Django 4.1.3 on 2022-12-04 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StillMinutePhotographs', '0004_alter_eventsimages_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmsLinks',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('SubCategory', models.CharField(blank=True, default='', max_length=100)),
                ('YoutubeEmbeddLink', models.CharField(default='', max_length=800)),
                ('PictureName', models.CharField(blank=True, default='', max_length=200)),
                ('PhotoGrapher', models.CharField(blank=True, default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Short_Description', models.CharField(blank=True, default='', max_length=500)),
                ('Display_in_Products_Page', models.BooleanField(default=True)),
                ('UploadDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Film Links',
            },
        ),
        migrations.AlterModelOptions(
            name='eventsimages',
            options={'verbose_name_plural': 'Event Images'},
        ),
        migrations.AlterModelOptions(
            name='fineartimages',
            options={'verbose_name_plural': 'Fine Art Images'},
        ),
        migrations.AlterModelOptions(
            name='foodimages',
            options={'verbose_name_plural': 'Food Images'},
        ),
        migrations.AlterModelOptions(
            name='interiorsimages',
            options={'verbose_name_plural': 'Interior Images'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='weddingimages',
            options={'verbose_name_plural': 'Wedding Images'},
        ),
        migrations.RenameField(
            model_name='eventsimages',
            old_name='ProductName',
            new_name='PictureName',
        ),
        migrations.RenameField(
            model_name='fineartimages',
            old_name='ProductName',
            new_name='PictureName',
        ),
        migrations.RenameField(
            model_name='foodimages',
            old_name='ProductName',
            new_name='PictureName',
        ),
        migrations.RenameField(
            model_name='interiorsimages',
            old_name='ProductName',
            new_name='PictureName',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='ProductName',
            new_name='PictureName',
        ),
        migrations.RenameField(
            model_name='weddingimages',
            old_name='ProductName',
            new_name='PictureName',
        ),
    ]
