# Generated by Django 4.1.3 on 2022-12-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StillMinutePhotographs', '0005_filmslinks_alter_eventsimages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmslinks',
            name='UploadDate',
        ),
    ]
