# Generated by Django 4.1.3 on 2022-12-04 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StillMinutePhotographs', '0006_remove_filmslinks_uploaddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmslinks',
            name='Date',
        ),
        migrations.AddField(
            model_name='filmslinks',
            name='UploadDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
