# Generated by Django 4.1.3 on 2022-12-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StillMinutePhotographs', '0007_remove_filmslinks_date_filmslinks_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsimages',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='fineartimages',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='foodimages',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='interiorsimages',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='weddingimages',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
