# Generated by Django 4.1.3 on 2022-12-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StillMinutePhotographs', '0008_alter_eventsimages_image_alter_fineartimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interiorsimages',
            name='SubCategory',
            field=models.CharField(choices=[('CommercialAndResidentialSpaces', 'Commercial And Residential Spaces'), ('InstallationArt', 'Installation Art')], default='', max_length=50),
        ),
    ]
