# Generated by Django 4.1.3 on 2022-12-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StillMinutePhotographs', '0009_alter_interiorsimages_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientele',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, default='', max_length=200)),
                ('Image', models.ImageField(default='', upload_to='')),
                ('UploadDate', models.DateTimeField(auto_now_add=True)),
                ('Display_in_Products_Page', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clientele',
            },
        ),
    ]
